// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcFood.Data;

namespace MvcFood.Migrations
{
    [DbContext(typeof(MvcFoodContext))]
    [Migration("20220429172036_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcFood.Models.Food", b =>
                {
                    b.Property<int>("fdcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fdcId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("MvcFood.Models.Food_Nutrient", b =>
                {
                    b.Property<int>("FNId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("foodfdcId")
                        .HasColumnType("int");

                    b.Property<int?>("nutrientId")
                        .HasColumnType("int");

                    b.Property<string>("unitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("value")
                        .HasColumnType("real");

                    b.HasKey("FNId");

                    b.HasIndex("foodfdcId");

                    b.HasIndex("nutrientId");

                    b.ToTable("Food_Nutrient");
                });

            modelBuilder.Entity("MvcFood.Models.Nutrient", b =>
                {
                    b.Property<int>("nutrientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nutrientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nutrientNumber")
                        .HasColumnType("int");

                    b.HasKey("nutrientId");

                    b.ToTable("Nutrient");
                });

            modelBuilder.Entity("MvcFood.Models.Food_Nutrient", b =>
                {
                    b.HasOne("MvcFood.Models.Food", "food")
                        .WithMany("food_nutrients")
                        .HasForeignKey("foodfdcId");

                    b.HasOne("MvcFood.Models.Nutrient", "nutrient")
                        .WithMany("food_nutrients")
                        .HasForeignKey("nutrientId");

                    b.Navigation("food");

                    b.Navigation("nutrient");
                });

            modelBuilder.Entity("MvcFood.Models.Food", b =>
                {
                    b.Navigation("food_nutrients");
                });

            modelBuilder.Entity("MvcFood.Models.Nutrient", b =>
                {
                    b.Navigation("food_nutrients");
                });
#pragma warning restore 612, 618
        }
    }
}
